spring:
  application:
    name: samples-kafka

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: "localhost:9092"
      max-poll-records: 500
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: latest
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: hipravin.sampleskafka.dto.ClockTickEvent
        spring.json.trusted.packages: "hipravin.sampleskafka.dto"
        spring.json.use.type.headers: false
    listener:
      ack-mode: batch #record ack is about 1000 times slower than batch

#      enable-auto-commit: true #default false, but someone is saying it's not sufficient https://stackoverflow.com/questions/61885717/kafka-consumer-with-enable-auto-commit-false-still-committing-the-offsets

application:
  clock-producer:
    message-count: 20_000
    enabled: true